name: novo
description: "Minimalistic PDF viewer app"
publish_to: "none"
version: 1.0.4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
  pdfrx: ^1.1.23
  file_picker: ^10.1.2
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
      ref: 2cea396843cd3ab1b5ec4334be4233864637874e

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.2

flutter:
  uses-material-design: true
